/*
 * generated by Xtext 2.9.2
 */
package hu.bme.mdsd.drone.ui.tests;

import com.google.inject.Injector;
import hu.bme.mdsd.ztz.text.ui.internal.TextActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class BehaviourLanguageUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TextActivator.getInstance().getInjector("hu.bme.mdsd.drone.BehaviourLanguage");
	}

}
