/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mdsd.ztz.text.behaviourLanguage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see hu.bme.mdsd.ztz.text.behaviourLanguage.BehaviourLanguageFactory
 * @model kind="package"
 * @generated
 */
public interface BehaviourLanguagePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "behaviourLanguage";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.mdsd.hu/behaviour/language";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "behaviourLanguage";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BehaviourLanguagePackage eINSTANCE = hu.bme.mdsd.ztz.text.behaviourLanguage.impl.BehaviourLanguagePackageImpl.init();

  /**
   * The meta object id for the '{@link hu.bme.mdsd.ztz.text.behaviourLanguage.impl.BehaviourLanguageImpl <em>Behaviour Language</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mdsd.ztz.text.behaviourLanguage.impl.BehaviourLanguageImpl
   * @see hu.bme.mdsd.ztz.text.behaviourLanguage.impl.BehaviourLanguagePackageImpl#getBehaviourLanguage()
   * @generated
   */
  int BEHAVIOUR_LANGUAGE = 0;

  /**
   * The feature id for the '<em><b>Import Model</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEHAVIOUR_LANGUAGE__IMPORT_MODEL = 0;

  /**
   * The feature id for the '<em><b>Container</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEHAVIOUR_LANGUAGE__CONTAINER = 1;

  /**
   * The number of structural features of the '<em>Behaviour Language</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEHAVIOUR_LANGUAGE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link hu.bme.mdsd.ztz.text.behaviourLanguage.impl.ImportImpl <em>Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mdsd.ztz.text.behaviourLanguage.impl.ImportImpl
   * @see hu.bme.mdsd.ztz.text.behaviourLanguage.impl.BehaviourLanguagePackageImpl#getImport()
   * @generated
   */
  int IMPORT = 1;

  /**
   * The feature id for the '<em><b>Import URI</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT__IMPORT_URI = 0;

  /**
   * The number of structural features of the '<em>Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link hu.bme.mdsd.ztz.text.behaviourLanguage.BehaviourLanguage <em>Behaviour Language</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Behaviour Language</em>'.
   * @see hu.bme.mdsd.ztz.text.behaviourLanguage.BehaviourLanguage
   * @generated
   */
  EClass getBehaviourLanguage();

  /**
   * Returns the meta object for the containment reference '{@link hu.bme.mdsd.ztz.text.behaviourLanguage.BehaviourLanguage#getImportModel <em>Import Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Import Model</em>'.
   * @see hu.bme.mdsd.ztz.text.behaviourLanguage.BehaviourLanguage#getImportModel()
   * @see #getBehaviourLanguage()
   * @generated
   */
  EReference getBehaviourLanguage_ImportModel();

  /**
   * Returns the meta object for the containment reference '{@link hu.bme.mdsd.ztz.text.behaviourLanguage.BehaviourLanguage#getContainer <em>Container</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Container</em>'.
   * @see hu.bme.mdsd.ztz.text.behaviourLanguage.BehaviourLanguage#getContainer()
   * @see #getBehaviourLanguage()
   * @generated
   */
  EReference getBehaviourLanguage_Container();

  /**
   * Returns the meta object for class '{@link hu.bme.mdsd.ztz.text.behaviourLanguage.Import <em>Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import</em>'.
   * @see hu.bme.mdsd.ztz.text.behaviourLanguage.Import
   * @generated
   */
  EClass getImport();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.mdsd.ztz.text.behaviourLanguage.Import#getImportURI <em>Import URI</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Import URI</em>'.
   * @see hu.bme.mdsd.ztz.text.behaviourLanguage.Import#getImportURI()
   * @see #getImport()
   * @generated
   */
  EAttribute getImport_ImportURI();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BehaviourLanguageFactory getBehaviourLanguageFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link hu.bme.mdsd.ztz.text.behaviourLanguage.impl.BehaviourLanguageImpl <em>Behaviour Language</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mdsd.ztz.text.behaviourLanguage.impl.BehaviourLanguageImpl
     * @see hu.bme.mdsd.ztz.text.behaviourLanguage.impl.BehaviourLanguagePackageImpl#getBehaviourLanguage()
     * @generated
     */
    EClass BEHAVIOUR_LANGUAGE = eINSTANCE.getBehaviourLanguage();

    /**
     * The meta object literal for the '<em><b>Import Model</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BEHAVIOUR_LANGUAGE__IMPORT_MODEL = eINSTANCE.getBehaviourLanguage_ImportModel();

    /**
     * The meta object literal for the '<em><b>Container</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BEHAVIOUR_LANGUAGE__CONTAINER = eINSTANCE.getBehaviourLanguage_Container();

    /**
     * The meta object literal for the '{@link hu.bme.mdsd.ztz.text.behaviourLanguage.impl.ImportImpl <em>Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mdsd.ztz.text.behaviourLanguage.impl.ImportImpl
     * @see hu.bme.mdsd.ztz.text.behaviourLanguage.impl.BehaviourLanguagePackageImpl#getImport()
     * @generated
     */
    EClass IMPORT = eINSTANCE.getImport();

    /**
     * The meta object literal for the '<em><b>Import URI</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT__IMPORT_URI = eINSTANCE.getImport_ImportURI();

  }

} //BehaviourLanguagePackage
