/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mdsd.ztz.text.behaviourLanguage;

import hu.bme.mdsd.ztz.model.behaviour.TaskExecution;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Execution Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mdsd.ztz.text.behaviourLanguage.ExecutionStatement#getExecution <em>Execution</em>}</li>
 * </ul>
 *
 * @see hu.bme.mdsd.ztz.text.behaviourLanguage.BehaviourLanguagePackage#getExecutionStatement()
 * @model
 * @generated
 */
public interface ExecutionStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Execution</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Execution</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Execution</em>' reference.
   * @see #setExecution(TaskExecution)
   * @see hu.bme.mdsd.ztz.text.behaviourLanguage.BehaviourLanguagePackage#getExecutionStatement_Execution()
   * @model
   * @generated
   */
  TaskExecution getExecution();

  /**
   * Sets the value of the '{@link hu.bme.mdsd.ztz.text.behaviourLanguage.ExecutionStatement#getExecution <em>Execution</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Execution</em>' reference.
   * @see #getExecution()
   * @generated
   */
  void setExecution(TaskExecution value);

} // ExecutionStatement
