/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mdsd.ztz.text.behaviourLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Message Target</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see hu.bme.mdsd.ztz.text.behaviourLanguage.BehaviourLanguagePackage#getMessageTarget()
 * @model
 * @generated
 */
public interface MessageTarget extends EObject
{
} // MessageTarget
