/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mdsd.ztz.text.behaviourLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Status Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see hu.bme.mdsd.ztz.text.behaviourLanguage.BehaviourLanguagePackage#getStatusStatement()
 * @model
 * @generated
 */
public interface StatusStatement extends AtomicStatement
{
} // StatusStatement
