<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="behaviourModel" nsURI="http://www.mdsd.hu/behaviour" nsPrefix="behaviourModel">
  <eClassifiers xsi:type="ecore:EClass" name="Unicast" eSuperTypes="#//CommunicationAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="robotToNotify" lowerBound="1"
        eType="ecore:EClass drone.ecore#//Robot"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Multicast" eSuperTypes="#//CommunicationAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="robotsToNotify" upperBound="-1"
        eType="ecore:EClass drone.ecore#//Robot"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Broadcast" eSuperTypes="#//CommunicationAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="robotsToNotify" upperBound="-1"
        eType="ecore:EClass drone.ecore#//Robot"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationAction" eSuperTypes="drone.ecore#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="messages" lowerBound="1"
        eType="#//Message" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="ecore:EClass drone.ecore#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="ecore:EClass drone.ecore#//Task"/>
  </eClassifiers>
</ecore:EPackage>
