/*
 * generated by Xtext 2.9.2
 */
package hu.bme.mdsd.drone


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class BehaviourLanguageRuntimeModule extends AbstractBehaviourLanguageRuntimeModule {
}
