/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mdsd.ztz.text.behaviourLanguage.impl;

import hu.bme.mdsd.ztz.model.behaviour.DynamicRobot;
import hu.bme.mdsd.ztz.model.behaviour.RobotStatus;

import hu.bme.mdsd.ztz.text.behaviourLanguage.BehaviourLanguagePackage;
import hu.bme.mdsd.ztz.text.behaviourLanguage.RobotStatusCondition;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Robot Status Condition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mdsd.ztz.text.behaviourLanguage.impl.RobotStatusConditionImpl#getRobot <em>Robot</em>}</li>
 *   <li>{@link hu.bme.mdsd.ztz.text.behaviourLanguage.impl.RobotStatusConditionImpl#getRobotStatus <em>Robot Status</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RobotStatusConditionImpl extends ConditionImpl implements RobotStatusCondition
{
  /**
   * The cached value of the '{@link #getRobot() <em>Robot</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRobot()
   * @generated
   * @ordered
   */
  protected DynamicRobot robot;

  /**
   * The default value of the '{@link #getRobotStatus() <em>Robot Status</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRobotStatus()
   * @generated
   * @ordered
   */
  protected static final RobotStatus ROBOT_STATUS_EDEFAULT = RobotStatus.READY;

  /**
   * The cached value of the '{@link #getRobotStatus() <em>Robot Status</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRobotStatus()
   * @generated
   * @ordered
   */
  protected RobotStatus robotStatus = ROBOT_STATUS_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RobotStatusConditionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BehaviourLanguagePackage.Literals.ROBOT_STATUS_CONDITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DynamicRobot getRobot()
  {
    if (robot != null && robot.eIsProxy())
    {
      InternalEObject oldRobot = (InternalEObject)robot;
      robot = (DynamicRobot)eResolveProxy(oldRobot);
      if (robot != oldRobot)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, BehaviourLanguagePackage.ROBOT_STATUS_CONDITION__ROBOT, oldRobot, robot));
      }
    }
    return robot;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DynamicRobot basicGetRobot()
  {
    return robot;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRobot(DynamicRobot newRobot)
  {
    DynamicRobot oldRobot = robot;
    robot = newRobot;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BehaviourLanguagePackage.ROBOT_STATUS_CONDITION__ROBOT, oldRobot, robot));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RobotStatus getRobotStatus()
  {
    return robotStatus;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRobotStatus(RobotStatus newRobotStatus)
  {
    RobotStatus oldRobotStatus = robotStatus;
    robotStatus = newRobotStatus == null ? ROBOT_STATUS_EDEFAULT : newRobotStatus;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BehaviourLanguagePackage.ROBOT_STATUS_CONDITION__ROBOT_STATUS, oldRobotStatus, robotStatus));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BehaviourLanguagePackage.ROBOT_STATUS_CONDITION__ROBOT:
        if (resolve) return getRobot();
        return basicGetRobot();
      case BehaviourLanguagePackage.ROBOT_STATUS_CONDITION__ROBOT_STATUS:
        return getRobotStatus();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BehaviourLanguagePackage.ROBOT_STATUS_CONDITION__ROBOT:
        setRobot((DynamicRobot)newValue);
        return;
      case BehaviourLanguagePackage.ROBOT_STATUS_CONDITION__ROBOT_STATUS:
        setRobotStatus((RobotStatus)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BehaviourLanguagePackage.ROBOT_STATUS_CONDITION__ROBOT:
        setRobot((DynamicRobot)null);
        return;
      case BehaviourLanguagePackage.ROBOT_STATUS_CONDITION__ROBOT_STATUS:
        setRobotStatus(ROBOT_STATUS_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BehaviourLanguagePackage.ROBOT_STATUS_CONDITION__ROBOT:
        return robot != null;
      case BehaviourLanguagePackage.ROBOT_STATUS_CONDITION__ROBOT_STATUS:
        return robotStatus != ROBOT_STATUS_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (robotStatus: ");
    result.append(robotStatus);
    result.append(')');
    return result.toString();
  }

} //RobotStatusConditionImpl
