/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mdsd.ztz.text;

import hu.bme.mdsd.ztz.text.AbstractBehaviourLanguageRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class BehaviourLanguageRuntimeModule extends AbstractBehaviourLanguageRuntimeModule {
}
