<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="instance">
  <eClassifiers xsi:type="ecore:EClass" name="Rover" eSuperTypes="#//Robot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wheel" lowerBound="4" upperBound="8"
        eType="#//Wheel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mechanicalarm" eType="#//MechanicalArm"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Drone" eSuperTypes="#//Robot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wing" lowerBound="2" upperBound="2"
        eType="#//Wing">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Robot"/>
  <eClassifiers xsi:type="ecore:EClass" name="Equipment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="#//Action"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Wing" eSuperTypes="#//Equipment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fly" eType="#//Fly"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="move" eType="#//Move"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Wheel" eSuperTypes="#//Equipment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="move" eType="#//Move"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MechanicalArm" eSuperTypes="#//Equipment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="catch" eType="#//Catch"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fly" eSuperTypes="#//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="Move" eSuperTypes="#//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="Catch" eSuperTypes="#//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyValue" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="MeasureProperty" eSuperTypes="#//PropertyValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="ecore:EClass ../model/drone.ecore#//MeasureValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringProperty" eSuperTypes="#//PropertyValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
